sudo: required
services:
  -docker
language: generic

before_install:
  - docker build -t sotkou/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sotkou/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-550921098483"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY