sudo: required
services:
  -docker

before_install:
  - docker build -t sotkou/docker-react -f Dockerfile.dev .

script:
  -  - docker run -e CI=true sotkou/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-550921098483"
  bucket_path: "dockerreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"